version: "3.1"
services:
  db:
    image: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin4
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: admin4

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
